### ISSUE TITLE
Confusion about training Voxel-Flow for multi-frame prediction

### ISSUE THREAD

**Issue by zzwei1** [YueWuHKUST/FutureVideoSynthesis#1]
Nice work!
I'm doing some research about radar echo extrapolation which could be seen as a video prediction problem. I wonna train Voxel Flow on my dataset for multi-frame predition. My task is predicting  the following 10 frames given the first 5 frames as input. I notice you re-trained the Voxel-Flow for multi-frame prediction in this paper. However, I don't know how to train it for multi-frame prediction.
What confused me is that, how should I make multi-frame prediction using Voxel-Flow? When I have the first 5 frames as input, I concat them along time dimension, and then followed the precedure in Voxel-Flow to generate the fiest predicted frame. I understand so far. But what should I do next to generate the second, third frames? Should I concat the first predicted frame with the 5 ground truth frames to generate a new input? I don't think it's correct because the input channels will be changed if I do so.
Thanks in advance!

**Comment by YueWuHKUST** [comment]
Thanks for your interest in my work! You can test recurrently, for example, you can concat the last 4 frames and the first predicted frame to generate the second predicted frame.
