### ISSUE TITLE
Static map background prediction

### ISSUE THREAD

**Issue by PierfrancescoArdino** [YueWuHKUST/FutureVideoSynthesis#6]
Hi,

I think there is a bug in the temporal_dataset for the background prediction. 

In the `load_all_image_paths` function at `line 180` this line of code will load the paths for the static map 
```
for p in range(len(static_dirs)):
       static_video = sorted(glob.glob(full_static_dir + static_dirs[p] + '/*.png'))
```
The problem is that each time `static_video` is overwritten, meaning that will we get the last 9 frames (t_in = 4 and t_out=5) of the video. this would cause a mismatch between the frames and the static mask. 

Indeed, while we load the `image_path` in the correct way:
```
start_idx = np.random.randint(0, self.n_frames_total - tAll)
image_path = image_paths[start_idx + i]
```
for the ```static_map``` we just load the ```i``` frame, this will cause a mismatch.
```
static_path = static_paths[i]
```

I think one possibe solution is to change ```line 181``` to this:

```
for p in range(len(static_dirs)):
 static_video.append(sorted(glob.glob(full_static_dir + static_dirs[p] + '/*.png')))
```

and ```line 74``` to this:

```
static_path = static_paths[start_idx][i]
```

**Comment by kathrinawu** [comment]
Oh, thanks! You are correct. The code is updated. The pretrained model should be fine; previously, the files were not organized in this way.
